default_agent: Test_Agent
agents:
  Test_Agent:
    name: Test_Agent
    entrypoint: /home/ritik/Documents/test sentra/Backend/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::628897991744:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-eea9edbb79
      execution_role_auto_create: false
      account: '628897991744'
      region: ap-south-1
      ecr_repository: 628897991744.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-test_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: Test_Agent-LNZiEg4CnQ
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:628897991744:runtime/Test_Agent-LNZiEg4CnQ
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-test_agent-builder
      execution_role: arn:aws:iam::628897991744:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-eea9edbb79
      source_bucket: bedrock-agentcore-codebuild-sources-628897991744-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
